# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9da19365160d4cc3065430490e4b4b858525bd7f5efa1b0e1cd8328c26767447df0003a318a0568173d859a2899bc67c3a89caae2df99123e3016787dc8a3401

test:
  secret_key_base: dfa763d2a472825eb7c42a4be51805ec7d7f407b552315fce63f00a2ae3d19285f4e529c699fce8ef6f98ba181db1598ed19f3fc83c503195af9c9f8769edabb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
